title: Benjamin Yi

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/benjyi"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"  
 - name: "Projects"
   link: "/projects"
 - name: "Resume"
   link: "/resume.pdf"
 - name: "Contact"
   link: "/contact"
