title: Benjamin Yi

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/benjyi"
footer_text: "Benjamin "

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Projects"
   link: "/projects"
 - name: "Resume"
   link: "/resume.pdf"
 - name: "Contact"
   link: "/contact"
